"""Atomically add the NutriDulce and Nitro Coffee business catalog to PostgreSQL."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from backend.server import connect  # noqa: E402


def migrate() -> None:
    # One connection context owns the entire migration transaction. Any exception
    # rolls back its DDL and data changes together.
    with connect() as db:
        required_tables = db.execute("""SELECT
            to_regclass('public.products') AS products_table,
            to_regclass('public.users') AS users_table""").fetchone()
        if not required_tables["products_table"] or not required_tables["users_table"]:
            raise RuntimeError("La base debe tener las tablas products y users antes de esta migración.")

        user_duplicates = db.execute("""SELECT lower(username) AS username, COUNT(*) AS count
            FROM users GROUP BY lower(username) HAVING COUNT(*)>1 LIMIT 1""").fetchone()
        if user_duplicates:
            raise RuntimeError(
                "Hay usuarios duplicados ignorando mayúsculas/minúsculas "
                f"({user_duplicates['username']}); corregilos antes de aplicar el índice único."
            )

        db.execute("""CREATE TABLE IF NOT EXISTS businesses (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL UNIQUE,
            description TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
        )""")
        db.execute("""INSERT INTO businesses(slug,name,description) VALUES
            ('nutridulce','NutriDulce','Repostería casera.'),
            ('nitro-coffee','Nitro Coffee','Café y bebidas de Nitro Sport.')
            ON CONFLICT(slug) DO NOTHING""")

        db.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS business_id BIGINT REFERENCES businesses(id)")
        dulce_id = db.execute("SELECT id FROM businesses WHERE slug='nutridulce'").fetchone()["id"]
        nitro_id = db.execute("SELECT id FROM businesses WHERE slug='nitro-coffee'").fetchone()["id"]

        # Detect collisions using the business each legacy NULL row will receive.
        # This happens before the backfill; raising here rolls back the whole transaction.
        product_duplicates = db.execute("""WITH target_products AS (
            SELECT CASE WHEN business_id IS NULL THEN %s ELSE business_id END AS target_business_id,
                lower(name) AS normalized_name
            FROM products
        )
        SELECT target_business_id, normalized_name, COUNT(*) AS count
        FROM target_products
        GROUP BY target_business_id, normalized_name
        HAVING COUNT(*)>1 LIMIT 1""", (dulce_id,)).fetchone()
        if product_duplicates:
            raise RuntimeError(
                "Hay productos duplicados dentro del mismo negocio "
                f"({product_duplicates['normalized_name']}); corregilos antes de aplicar el índice único."
            )

        db.execute("UPDATE products SET business_id=%s WHERE business_id IS NULL", (dulce_id,))
        db.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_products_business_name_ci ON products(business_id, lower(name))")

        # Match only Nitro Coffee rows; never move or reuse a NutriDulce product.
        for name, price, description in (("Agua", 5000, "Agua"), ("Café Espresso", 8000, "350 ml")):
            product = db.execute("""SELECT id FROM products
                WHERE business_id=%s AND lower(name)=lower(%s) ORDER BY id LIMIT 1""", (nitro_id, name)).fetchone()
            if not product:
                db.execute("""INSERT INTO products(
                    business_id,name,description,price,stock,image,active,low_stock_threshold
                ) VALUES (%s,%s,%s,%s,0,'photo-pending',1,5) ON CONFLICT DO NOTHING""",
                    (nitro_id, name, description, price))

        null_products = db.execute("SELECT 1 FROM products WHERE business_id IS NULL LIMIT 1").fetchone()
        if null_products:
            raise RuntimeError("Quedaron productos sin negocio asociado; no se aplicaron los cambios.")
        db.execute("ALTER TABLE products ALTER COLUMN business_id SET NOT NULL")
        db.execute("CREATE INDEX IF NOT EXISTS idx_products_business ON products(business_id)")

        # Check again immediately before creating the case-insensitive unique index.
        user_duplicates = db.execute("""SELECT lower(username) AS username, COUNT(*) AS count
            FROM users GROUP BY lower(username) HAVING COUNT(*)>1 LIMIT 1""").fetchone()
        if user_duplicates:
            raise RuntimeError(
                "Hay usuarios duplicados ignorando mayúsculas/minúsculas "
                f"({user_duplicates['username']}); corregilos antes de aplicar el índice único."
            )
        db.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_ci ON users(lower(username))")

    print("Migración multi-negocio completada. Datos anteriores conservados; catálogo listo.")


if __name__ == "__main__":
    migrate()
