"""NutriDulce API server backed by PostgreSQL."""
from __future__ import annotations

import hashlib
import hmac
import json
import os
import re
import secrets
import threading
import base64
import binascii
import psycopg
from datetime import date, datetime, timedelta
from decimal import Decimal
from http import HTTPStatus
from http.cookies import SimpleCookie
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse
from psycopg.rows import dict_row

ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = ROOT / "frontend"
SESSIONS: dict[str, str] = {}
DB_LOCK = threading.RLock()
PAYMENTS = {"Efectivo", "Transferencia", "Tarjeta"}
STATUSES = {"Pendiente", "Confirmado", "En preparación", "Listo para entregar", "Entregado", "Cancelado"}


def json_default(value):
    if isinstance(value, Decimal):
        return float(value)
    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


def password_hash(password, iterations=600000):
    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, iterations).hex()
    return f"pbkdf2_sha256${iterations}${salt.hex()}${digest}"


def verify_password(password, stored):
    try:
        if stored.startswith("pbkdf2_sha256$"):
            _, rounds, salt, expected = stored.split("$", 3)
            actual = hashlib.pbkdf2_hmac("sha256", password.encode(), bytes.fromhex(salt), int(rounds)).hex()
        else:  # Existing SQLite/PostgreSQL accounts use salt:digest with 240,000 rounds.
            salt, expected = stored.split(":", 1)
            actual = hashlib.pbkdf2_hmac("sha256", password.encode(), bytes.fromhex(salt), 240000).hex()
        return hmac.compare_digest(actual, expected)
    except (ValueError, TypeError):
        return False


def connect():
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if not database_url:
        raise RuntimeError("Falta configurar la variable de entorno DATABASE_URL con la conexión a PostgreSQL.")
    if database_url.startswith("postgres://"):
        database_url = "postgresql://" + database_url[len("postgres://"):]
    return psycopg.connect(
        database_url,
        connect_timeout=10,
        row_factory=dict_row,
        options="-c timezone=UTC",
    )


def init_db(seed_data=True):
    schema = [
        """CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
        )""",
        """CREATE TABLE IF NOT EXISTS payment_methods (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT UNIQUE NOT NULL
        )""",
        """CREATE TABLE IF NOT EXISTS products (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            price BIGINT NOT NULL CHECK (price >= 0),
            stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
            image TEXT NOT NULL DEFAULT '',
            active INTEGER NOT NULL DEFAULT 1,
            low_stock_threshold INTEGER NOT NULL DEFAULT 5,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
        )""",
        """CREATE TABLE IF NOT EXISTS customers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            phone TEXT UNIQUE NOT NULL,
            address TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
        )""",
        """CREATE TABLE IF NOT EXISTS orders (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT UNIQUE NOT NULL,
            customer_id BIGINT NOT NULL REFERENCES customers(id),
            payment_method TEXT NOT NULL,
            delivery_address TEXT NOT NULL,
            notes TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'Pendiente',
            total BIGINT NOT NULL CHECK (total >= 0),
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
        )""",
        """CREATE TABLE IF NOT EXISTS order_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            order_id BIGINT NOT NULL REFERENCES orders(id),
            product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
            product_name TEXT NOT NULL,
            quantity INTEGER NOT NULL CHECK (quantity > 0),
            unit_price BIGINT NOT NULL CHECK (unit_price >= 0)
        )""",
        """CREATE TABLE IF NOT EXISTS sales (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id),
            customer_id BIGINT NOT NULL REFERENCES customers(id),
            payment_method TEXT NOT NULL,
            status TEXT NOT NULL,
            total BIGINT NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
        )""",
        """CREATE TABLE IF NOT EXISTS sale_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sale_id BIGINT NOT NULL REFERENCES sales(id),
            product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
            product_name TEXT NOT NULL,
            quantity INTEGER NOT NULL,
            unit_price BIGINT NOT NULL
        )""",
        """CREATE TABLE IF NOT EXISTS stock_movements (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
            product_name TEXT NOT NULL,
            quantity_change INTEGER NOT NULL,
            reason TEXT NOT NULL,
            order_id BIGINT REFERENCES orders(id),
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
        )""",
        """CREATE TABLE IF NOT EXISTS expenses (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            category TEXT NOT NULL,
            amount BIGINT NOT NULL CHECK (amount >= 0),
            date DATE NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
        )""",
        "CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at)",
        "CREATE INDEX IF NOT EXISTS idx_sales_created ON sales(created_at)",
        "CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items(product_id)",
    ]
    with connect() as db:
        for statement in schema:
            db.execute(statement)
        if seed_data:
            businesses_table = db.execute("SELECT to_regclass('public.businesses') AS table_name").fetchone()["table_name"]
            product_business_column = db.execute("SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='products' AND column_name='business_id'").fetchone()
            if not businesses_table or not product_business_column:
                raise RuntimeError("Falta la migración de negocios. Ejecutá primero: python backend/migrate_multibusiness.py")
            for name in PAYMENTS:
                db.execute("INSERT INTO payment_methods(name) VALUES (%s) ON CONFLICT(name) DO NOTHING", (name,))
            if db.execute("SELECT COUNT(*) AS count FROM users").fetchone()["count"] == 0:
                username = os.environ.get("NUTRIDULCE_ADMIN_USER", "").strip()
                password = os.environ.get("NUTRIDULCE_ADMIN_PASSWORD", "")
                if username and password:
                    db.execute("INSERT INTO users(username,password_hash) VALUES (%s,%s)", (username, password_hash(password)))
            business = db.execute("SELECT id FROM businesses WHERE slug='nutridulce'").fetchone()
            if business:
                initial = [
                    ("Budín de frutos secos", "Budín casero esponjoso con una mezcla generosa de frutos secos.", 10000, 12, "budin-frutos-marmolado", 5),
                    ("Budín marmolado", "La combinación perfecta de vainilla y chocolate, hecho en casa.", 10000, 12, "budin-frutos-marmolado", 5),
                    ("Pastafrola con dulce de leche", "Masa suave y dorada, rellena de dulce de leche.", 8000, 12, "photo-pending", 5),
                    ("Pastafrola con dulce de guayaba", "Un clásico artesanal con dulce de guayaba paraguaya.", 8000, 12, "pastafrola-guayaba", 5),
                    ("Galletitas de avena x3 unidades", "Tres galletitas de avena caseras, crocantes y deliciosas.", 10000, 15, "photo-pending", 5),
                ]
                for item in initial:
                    present = db.execute("SELECT 1 FROM products WHERE business_id=%s AND name=%s", (business["id"], item[0])).fetchone()
                    if not present:
                        db.execute("INSERT INTO products(business_id,name,description,price,stock,image,low_stock_threshold) VALUES (%s,%s,%s,%s,%s,%s,%s)", (business["id"], *item))
        # Move untouched starter images to the real customer photos and explicit photo placeholders.
        db.execute("UPDATE products SET image='budin-frutos-marmolado' WHERE name='Budín de frutos secos' AND image='cake'")
        db.execute("UPDATE products SET image='budin-frutos-marmolado' WHERE name='Budín marmolado' AND image='marble'")
        db.execute("UPDATE products SET image='photo-pending' WHERE name='Pastafrola con dulce de leche' AND image='pastafrola'")
        db.execute("UPDATE products SET image='pastafrola-guayaba' WHERE name='Pastafrola con dulce de guayaba' AND image='guava'")
        db.execute("UPDATE products SET image='photo-pending' WHERE name='Galletitas de avena x3 unidades' AND image='cookies'")


def serialize(row):
    if row is None:
        return None
    result = dict(row)
    for key, value in result.items():
        if isinstance(value, datetime):
            result[key] = value.isoformat(sep=" ", timespec="seconds")
        elif isinstance(value, date):
            result[key] = value.isoformat()
    return result


def integer(value, label, minimum=0):
    try:
        n = int(value)
    except (TypeError, ValueError):
        raise ValueError(f"{label}: ingresá un número válido.")
    if n < minimum:
        raise ValueError(f"{label}: el valor mínimo es {minimum}.")
    return n


def boolean(value, label):
    if isinstance(value, bool):
        return value
    if value in (0, 1):
        return bool(value)
    raise ValueError(f"{label}: seleccioná una opción válida.")


class Handler(BaseHTTPRequestHandler):
    server_version = "NutriDulce/1.0"

    def log_message(self, fmt, *args):
        print("%s - %s" % (self.address_string(), fmt % args))

    def send_json(self, data, status=200, headers=None):
        body = json.dumps(data, ensure_ascii=False, default=json_default).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        if headers:
            for k, v in headers.items(): self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    def body(self):
        try:
            n = int(self.headers.get("Content-Length", "0"))
            limit = 7_000_000 if urlparse(self.path).path == "/api/admin/images" else 1_000_000
            if n > limit: raise ValueError("La solicitud es demasiado grande.")
            return json.loads(self.rfile.read(n) or b"{}")
        except json.JSONDecodeError:
            raise ValueError("El formato de los datos no es válido.")

    def admin(self):
        cookie = SimpleCookie(self.headers.get("Cookie", ""))
        sid = cookie.get("nd_session")
        user = SESSIONS.get(sid.value) if sid else None
        if not user:
            self.send_json({"error": "Iniciá sesión para continuar."}, 401)
            return False
        return True

    def do_GET(self):
        path = unquote(urlparse(self.path).path)
        query = {k: v[0] for k, v in parse_qs(urlparse(self.path).query).items()}
        try:
            with DB_LOCK, connect() as db:
                if path == "/api/products":
                    business = query.get("business")
                    sql = "SELECT p.*,b.slug business_slug,b.name business_name FROM products p JOIN businesses b ON b.id=p.business_id WHERE p.active=1"
                    args = []
                    if business:
                        sql += " AND b.slug=%s"; args.append(business)
                    return self.send_json([serialize(r) for r in db.execute(sql+" ORDER BY p.id", args)])
                if path == "/api/businesses":
                    return self.send_json([serialize(r) for r in db.execute("SELECT id,slug,name FROM businesses ORDER BY id")])
                if path == "/api/admin/registration-status":
                    users = db.execute("SELECT COUNT(*) AS count FROM users").fetchone()["count"]
                    return self.send_json({"available": users == 0 or bool(os.environ.get("NUTRIDULCE_ADMIN_REGISTRATION_KEY")), "requires_invite": users > 0})
                if path == "/api/admin/me":
                    if not self.admin(): return
                    cookie = SimpleCookie(self.headers.get("Cookie", "")); sid = cookie.get("nd_session")
                    return self.send_json({"username": SESSIONS[sid.value]})
                if path.startswith("/api/admin/") and not self.admin(): return
                if path == "/api/admin/products":
                    return self.send_json([serialize(r) for r in db.execute("SELECT p.*,b.slug business_slug,b.name business_name FROM products p JOIN businesses b ON b.id=p.business_id ORDER BY p.id")])
                if path == "/api/admin/orders":
                    rows = db.execute("SELECT o.*,c.name customer_name,c.phone customer_phone,c.address customer_saved_address FROM orders o JOIN customers c ON c.id=o.customer_id ORDER BY o.created_at DESC")
                    result = [serialize(r) for r in rows]
                    for order in result:
                        order["items"] = [serialize(r) for r in db.execute("SELECT * FROM order_items WHERE order_id=%s", (order["id"],))]
                    return self.send_json(result)
                if path == "/api/admin/sales":
                    sql = "SELECT s.*,c.name customer_name,c.phone customer_phone FROM sales s JOIN customers c ON c.id=s.customer_id WHERE 1=1"
                    args = []
                    if query.get("from"): sql += " AND s.created_at::date >= %s"; args.append(date.fromisoformat(query["from"]))
                    if query.get("to"): sql += " AND s.created_at::date <= %s"; args.append(date.fromisoformat(query["to"]))
                    if query.get("customer"): sql += " AND c.name ILIKE %s"; args.append("%"+query["customer"]+"%")
                    if query.get("payment"): sql += " AND s.payment_method=%s"; args.append(query["payment"])
                    if query.get("status"): sql += " AND s.status=%s"; args.append(query["status"])
                    if query.get("product"): sql += " AND EXISTS(SELECT 1 FROM sale_items si WHERE si.sale_id=s.id AND si.product_name ILIKE %s)"; args.append("%"+query["product"]+"%")
                    result = [serialize(r) for r in db.execute(sql+" ORDER BY s.created_at DESC", args)]
                    for sale in result: sale["items"] = [serialize(r) for r in db.execute("SELECT * FROM sale_items WHERE sale_id=%s", (sale["id"],))]
                    return self.send_json(result)
                if path == "/api/admin/customers":
                    return self.send_json([serialize(r) for r in db.execute("""SELECT c.*,(SELECT COUNT(*) FROM orders o WHERE o.customer_id=c.id) order_count,(SELECT COALESCE(SUM(s.total),0) FROM sales s WHERE s.customer_id=c.id AND s.status!='Cancelado') total_spent FROM customers c ORDER BY c.name""")])
                customer_match = re.fullmatch(r"/api/admin/customers/(\d+)", path)
                if customer_match:
                    customer = db.execute("SELECT * FROM customers WHERE id=%s", (int(customer_match.group(1)),)).fetchone()
                    if not customer: return self.send_json({"error":"Cliente no encontrado."},404)
                    result = serialize(customer)
                    result["orders"] = [serialize(r) for r in db.execute("SELECT * FROM orders WHERE customer_id=%s ORDER BY created_at DESC", (customer["id"],))]
                    for order in result["orders"]:
                        order["items"] = [serialize(r) for r in db.execute("SELECT product_name,quantity,unit_price FROM order_items WHERE order_id=%s", (order["id"],))]
                    return self.send_json(result)
                if path == "/api/admin/expenses":
                    return self.send_json([serialize(r) for r in db.execute("SELECT * FROM expenses ORDER BY date DESC,id DESC")])
                if path == "/api/admin/stock":
                    return self.send_json([serialize(r) for r in db.execute("SELECT id,name,stock,low_stock_threshold FROM products ORDER BY stock,id")])
                if path == "/api/admin/dashboard":
                    today = date.today(); week = today - timedelta(days=6); month = today.replace(day=1)
                    day_sum = db.execute("SELECT COALESCE(SUM(total),0) AS total FROM sales WHERE status!='Cancelado' AND created_at::date=%s", (today,)).fetchone()["total"]
                    week_sum = db.execute("SELECT COALESCE(SUM(total),0) AS total FROM sales WHERE status!='Cancelado' AND created_at::date>=%s", (week,)).fetchone()["total"]
                    month_sum = db.execute("SELECT COALESCE(SUM(total),0) AS total FROM sales WHERE status!='Cancelado' AND created_at::date>=%s", (month,)).fetchone()["total"]
                    total = db.execute("SELECT COALESCE(SUM(total),0) AS total FROM sales WHERE status!='Cancelado'").fetchone()["total"]
                    count = db.execute("SELECT COUNT(*) AS count FROM orders").fetchone()["count"]
                    expenses = db.execute("SELECT COALESCE(SUM(amount),0) AS total FROM expenses").fetchone()["total"]
                    top = [serialize(r) for r in db.execute("SELECT product_name name,SUM(quantity) quantity FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE s.status!='Cancelado' GROUP BY product_name ORDER BY quantity DESC LIMIT 5")]
                    low = [serialize(r) for r in db.execute("SELECT id,name,stock,low_stock_threshold FROM products WHERE active=1 AND stock<=low_stock_threshold ORDER BY stock")]
                    payments = [serialize(r) for r in db.execute("SELECT payment_method name,COUNT(*) count,COALESCE(SUM(total),0) total FROM sales WHERE status!='Cancelado' GROUP BY payment_method")]
                    chart = []
                    for i in range(6,-1,-1):
                        d = today-timedelta(days=i)
                        amount = db.execute("SELECT COALESCE(SUM(total),0) AS total FROM sales WHERE status!='Cancelado' AND created_at::date=%s", (d,)).fetchone()["total"]
                        chart.append({"date":d.isoformat(),"label":d.strftime("%d/%m"),"total":amount})
                    return self.send_json({"today":day_sum,"week":week_sum,"month":month_sum,"total":total,"orders":count,"expenses":expenses,"profit":total-expenses,"top_products":top,"low_stock":low,"payments":payments,"chart":chart})
                if path == "/api/admin/stock/movements":
                    return self.send_json([serialize(r) for r in db.execute("SELECT * FROM stock_movements ORDER BY created_at DESC LIMIT 100")])
            if path == "/" or path.startswith("/"):
                target = (WEB_ROOT / ("index.html" if path == "/" else path.lstrip("/"))).resolve()
                if not str(target).startswith(str(WEB_ROOT.resolve())) or not target.is_file(): return self.send_error(404)
                content_type = {".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".svg":"image/svg+xml",".jpg":"image/jpeg",".jpeg":"image/jpeg",".png":"image/png",".webp":"image/webp"}.get(target.suffix,"application/octet-stream")
                data = target.read_bytes(); self.send_response(200); self.send_header("Content-Type",content_type); self.send_header("Content-Length",str(len(data))); self.end_headers(); self.wfile.write(data); return
        except (ValueError, psycopg.Error) as exc: return self.send_json({"error":str(exc)},400)
        return self.send_json({"error":"No encontrado."},404)

    def do_POST(self): self.dispatch_mutation("POST")
    def do_PUT(self): self.dispatch_mutation("PUT")
    def do_PATCH(self): self.dispatch_mutation("PATCH")
    def do_DELETE(self): self.dispatch_mutation("DELETE")

    def dispatch_mutation(self, method):
        path = unquote(urlparse(self.path).path)
        try:
            data = self.body() if method not in ("DELETE",) else {}
            with DB_LOCK, connect() as db:
                if path == "/api/admin/login" and method == "POST":
                    username = str(data.get("username", "")).strip()
                    row = db.execute("SELECT * FROM users WHERE lower(username)=lower(%s)", (username,)).fetchone()
                    valid = bool(row and verify_password(str(data.get("password", "")), row["password_hash"]))
                    if not valid: return self.send_json({"error":"Usuario o contraseña incorrectos."},401)
                    sid = secrets.token_urlsafe(32); SESSIONS[sid] = row["username"]
                    return self.send_json({"ok":True,"username":row["username"]},headers={"Set-Cookie":f"nd_session={sid}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=43200"})
                if path == "/api/admin/register" and method == "POST":
                    username = str(data.get("username", "")).strip()
                    password = str(data.get("password", ""))
                    confirmation = str(data.get("confirm_password", ""))
                    invite = str(data.get("invite_key", ""))
                    if not re.fullmatch(r"[A-Za-z0-9_.-]{3,32}", username):
                        raise ValueError("El usuario debe tener entre 3 y 32 caracteres: letras, números, punto, guion o guion bajo.")
                    if len(password) < 12 or len(password) > 200:
                        raise ValueError("La contraseña debe tener entre 12 y 200 caracteres.")
                    if password != confirmation:
                        raise ValueError("Las contraseñas no coinciden.")
                    db.execute("SELECT pg_advisory_xact_lock(836271904)")
                    existing_count = db.execute("SELECT COUNT(*) AS count FROM users").fetchone()["count"]
                    invite_key = os.environ.get("NUTRIDULCE_ADMIN_REGISTRATION_KEY", "")
                    if existing_count and (not invite_key or not hmac.compare_digest(invite, invite_key)):
                        raise ValueError("El registro de administradores requiere una clave de invitación configurada por el administrador del sistema.")
                    if db.execute("SELECT 1 FROM users WHERE lower(username)=lower(%s)", (username,)).fetchone():
                        raise ValueError("Ese nombre de usuario ya está en uso.")
                    db.execute("INSERT INTO users(username,password_hash) VALUES (%s,%s)", (username, password_hash(password)))
                    return self.send_json({"ok":True,"username":username},201)
                if path == "/api/admin/logout" and method == "POST":
                    cookie = SimpleCookie(self.headers.get("Cookie", "")); sid=cookie.get("nd_session")
                    if sid: SESSIONS.pop(sid.value,None)
                    return self.send_json({"ok":True},headers={"Set-Cookie":"nd_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0"})
                if path.startswith("/api/admin/") and not self.admin(): return
                if path == "/api/orders" and method == "POST":
                    name=str(data.get("name","")).strip(); phone=str(data.get("phone","")).strip(); address=str(data.get("address","")).strip(); payment=data.get("payment"); notes=str(data.get("notes","")).strip()
                    if not name or len(name)>100: raise ValueError("Ingresá el nombre del cliente (hasta 100 caracteres).")
                    if not re.fullmatch(r"[+0-9()\s-]{7,25}",phone): raise ValueError("Ingresá un número de teléfono válido.")
                    if not address or len(address)>250: raise ValueError("Ingresá una dirección o lugar de entrega.")
                    if payment not in PAYMENTS: raise ValueError("Seleccioná un método de pago válido.")
                    items=data.get("items")
                    if not isinstance(items,list) or not items: raise ValueError("El carrito está vacío.")
                    merged={}
                    for item in items:
                        pid=integer(item.get("product_id"),"Producto",1); qty=integer(item.get("quantity"),"Cantidad",1)
                        merged[pid]=merged.get(pid,0)+qty
                    lines=[]; total=0
                    for pid,qty in merged.items():
                        product=db.execute("SELECT * FROM products WHERE id=%s AND active=1",(pid,)).fetchone()
                        if not product: raise ValueError("Uno de los productos ya no está disponible. Actualizá el catálogo.")
                        if product["stock"]<qty: raise ValueError(f"Stock insuficiente para {product['name']}.")
                        lines.append((product,qty)); total+=product["price"]*qty
                    db.execute("INSERT INTO customers(name,phone,address) VALUES (%s,%s,%s) ON CONFLICT(phone) DO UPDATE SET name=excluded.name,address=excluded.address",(name,phone,address))
                    customer=db.execute("SELECT id FROM customers WHERE phone=%s",(phone,)).fetchone()["id"]
                    code="ND-"+datetime.now().strftime("%y%m%d")+"-"+secrets.token_hex(3).upper()
                    order_id=db.execute("INSERT INTO orders(code,customer_id,payment_method,delivery_address,notes,total) VALUES (%s,%s,%s,%s,%s,%s) RETURNING id",(code,customer,payment,address,notes,total)).fetchone()["id"]
                    for product,qty in lines: db.execute("INSERT INTO order_items(order_id,product_id,product_name,quantity,unit_price) VALUES (%s,%s,%s,%s,%s)",(order_id,product["id"],product["name"],qty,product["price"]))
                    return self.send_json({"ok":True,"code":code,"total":total,"message":"¡Pedido recibido! Te contactaremos para confirmar los detalles."},201)
                if path == "/api/admin/products" and method == "POST":
                    name=str(data.get("name","")).strip(); description=str(data.get("description","")).strip(); image=str(data.get("image","cake")).strip() or "cake"
                    if not name or len(name)>120: raise ValueError("El nombre del producto es obligatorio (hasta 120 caracteres).")
                    if len(description)>500 or len(image)>200: raise ValueError("La descripción o referencia de la imagen es demasiado extensa.")
                    price=integer(data.get("price"),"Precio"); stock=integer(data.get("stock"),"Stock"); threshold=integer(data.get("low_stock_threshold",5),"Aviso de poco stock")
                    business_id=integer(data.get("business_id"),"Negocio",1)
                    if not db.execute("SELECT 1 FROM businesses WHERE id=%s",(business_id,)).fetchone(): raise ValueError("Seleccioná un negocio válido.")
                    active=boolean(data.get("active",True),"Visibilidad")
                    product_id=db.execute("INSERT INTO products(business_id,name,description,price,stock,image,low_stock_threshold,active) VALUES (%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id",(business_id,name,description,price,stock,image,threshold,int(active))).fetchone()["id"]
                    if stock: db.execute("INSERT INTO stock_movements(product_id,product_name,quantity_change,reason) VALUES (%s,%s,%s,'Stock inicial')",(product_id,name,stock))
                    return self.send_json({"ok":True,"id":product_id},201)
                if path == "/api/admin/expenses" and method == "POST":
                    name=str(data.get("name","")).strip(); category=str(data.get("category","")).strip(); amount=integer(data.get("amount"),"Monto"); day=str(data.get("date",date.today().isoformat()))
                    if not name or not category: raise ValueError("Ingresá el nombre y la categoría del gasto.")
                    expense_date=date.fromisoformat(day)
                    expense_id=db.execute("INSERT INTO expenses(name,category,amount,date,description) VALUES (%s,%s,%s,%s,%s) RETURNING id",(name,category,amount,expense_date,str(data.get("description","")).strip())).fetchone()["id"]
                    return self.send_json({"ok":True,"id":expense_id},201)
                if path.startswith("/api/admin/"):
                    return self.admin_mutation(db,path,method,data)
        except (ValueError, psycopg.Error) as exc:
            return self.send_json({"error":str(exc)},400)
        return self.send_json({"error":"No encontrado."},404)

    def admin_mutation(self, db, path, method, data):
        if path == "/api/admin/images" and method == "POST":
            data_url = str(data.get("data", ""))
            image_match = re.fullmatch(r"data:(image/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)", data_url)
            if not image_match: raise ValueError("Elegí una imagen JPEG, PNG o WebP.")
            mime, payload = image_match.groups()
            try: raw = base64.b64decode(payload, validate=True)
            except (binascii.Error, ValueError): raise ValueError("El archivo de imagen no es válido.")
            if not raw or len(raw) > 5_000_000: raise ValueError("La imagen debe pesar 5 MB o menos.")
            signatures = {"image/jpeg": raw.startswith(b"\xff\xd8\xff"), "image/png": raw.startswith(b"\x89PNG\r\n\x1a\n"), "image/webp": len(raw) >= 12 and raw.startswith(b"RIFF") and raw[8:12] == b"WEBP"}
            if not signatures[mime]: raise ValueError("El contenido del archivo no coincide con su formato.")
            ext = {"image/jpeg":"jpg", "image/png":"png", "image/webp":"webp"}[mime]
            filename = f"product-{hashlib.sha256(raw).hexdigest()[:16]}.{ext}"
            (WEB_ROOT / "assets" / filename).write_bytes(raw)
            return self.send_json({"ok":True,"image":filename},201)
        match = re.fullmatch(r"/api/admin/products/(\d+)",path)
        if match:
            pid=int(match.group(1))
            p=db.execute("SELECT * FROM products WHERE id=%s"+(" FOR UPDATE" if method == "DELETE" else ""),(pid,)).fetchone()
            if not p: return self.send_json({"error":"Producto no encontrado."},404)
            if method == "DELETE":
                history=db.execute("""SELECT
                    (SELECT COUNT(*) FROM order_items WHERE product_id=%s) AS orders,
                    (SELECT COUNT(*) FROM sale_items WHERE product_id=%s) AS sales,
                    (SELECT COUNT(*) FROM stock_movements WHERE product_id=%s) AS movements""",(pid,pid,pid)).fetchone()
                if any(history.values()):
                    return self.send_json({"error":"No se puede eliminar físicamente este producto porque tiene historial de pedidos, ventas o movimientos de stock."},409)
                db.execute("DELETE FROM products WHERE id=%s",(pid,))
                return self.send_json({"ok":True,"message":"Producto eliminado."})
            if method == "PUT":
                name=str(data.get("name","")).strip(); description=str(data.get("description","")).strip(); price=integer(data.get("price"),"Precio"); stock=integer(data.get("stock"),"Stock"); threshold=integer(data.get("low_stock_threshold",5),"Aviso de poco stock")
                image=str(data.get("image","cake")).strip()
                if not name or len(name)>120: raise ValueError("El nombre del producto es obligatorio (hasta 120 caracteres).")
                if len(description)>500 or len(image)>200: raise ValueError("La descripción o referencia de la imagen es demasiado extensa.")
                business_id=integer(data.get("business_id",p["business_id"]),"Negocio",1)
                if not db.execute("SELECT 1 FROM businesses WHERE id=%s",(business_id,)).fetchone(): raise ValueError("Seleccioná un negocio válido.")
                active=boolean(data.get("active",True),"Visibilidad")
                if stock != p["stock"]: db.execute("INSERT INTO stock_movements(product_id,product_name,quantity_change,reason) VALUES (%s,%s,%s,%s)",(pid,name,stock-p["stock"],"Ajuste de stock"))
                db.execute("UPDATE products SET business_id=%s,name=%s,description=%s,price=%s,stock=%s,image=%s,active=%s,low_stock_threshold=%s,updated_at=CURRENT_TIMESTAMP WHERE id=%s",(business_id,name,description,price,stock,image,int(active),threshold,pid))
                return self.send_json({"ok":True})
        match=re.fullmatch(r"/api/admin/orders/(\d+)",path)
        if match and method == "PATCH":
            oid=int(match.group(1)); order=db.execute("SELECT * FROM orders WHERE id=%s",(oid,)).fetchone(); status=data.get("status")
            if not order: return self.send_json({"error":"Pedido no encontrado."},404)
            if status not in STATUSES: raise ValueError("El estado indicado no es válido.")
            if order["status"]=="Cancelado": raise ValueError("Un pedido cancelado no se puede reabrir.")
            allowed_next = {
                "Pendiente": {"Confirmado", "Cancelado"},
                "Confirmado": {"En preparación", "Cancelado"},
                "En preparación": {"Listo para entregar", "Cancelado"},
                "Listo para entregar": {"Entregado", "Cancelado"},
                "Entregado": set(),
            }
            if status == order["status"]:
                return self.send_json({"ok": True, "message": "El pedido ya tenía ese estado."})
            if status not in allowed_next[order["status"]]:
                raise ValueError("Ese cambio de estado no está permitido.")
            if status=="Confirmado" and order["status"]=="Pendiente":
                items=db.execute("SELECT * FROM order_items WHERE order_id=%s",(oid,)).fetchall()
                for item in items:
                    if item["product_id"] is not None:
                        product=db.execute("SELECT * FROM products WHERE id=%s",(item["product_id"],)).fetchone()
                        if not product or product["stock"]<item["quantity"]: raise ValueError(f"Stock insuficiente para {item['product_name']}. Actualizá el stock para confirmar.")
                db.execute("UPDATE orders SET status=%s,updated_at=CURRENT_TIMESTAMP WHERE id=%s",(status,oid))
                sale_id=db.execute("INSERT INTO sales(order_id,customer_id,payment_method,status,total) VALUES (%s,%s,%s,%s,%s) RETURNING id",(oid,order["customer_id"],order["payment_method"],status,order["total"])).fetchone()["id"]
                for item in items:
                    db.execute("INSERT INTO sale_items(sale_id,product_id,product_name,quantity,unit_price) VALUES (%s,%s,%s,%s,%s)",(sale_id,item["product_id"],item["product_name"],item["quantity"],item["unit_price"]))
                    if item["product_id"] is not None:
                        db.execute("UPDATE products SET stock=stock-%s,updated_at=CURRENT_TIMESTAMP WHERE id=%s",(item["quantity"],item["product_id"]))
                        db.execute("INSERT INTO stock_movements(product_id,product_name,quantity_change,reason,order_id) VALUES (%s,%s,%s,'Venta confirmada',%s)",(item["product_id"],item["product_name"],-item["quantity"],oid))
                return self.send_json({"ok":True,"message":"Pedido confirmado; venta registrada y stock actualizado."})
            if status=="Cancelado" and order["status"]!="Pendiente":
                items=db.execute("SELECT * FROM order_items WHERE order_id=%s",(oid,)).fetchall()
                for item in items:
                    if item["product_id"] is not None:
                        db.execute("UPDATE products SET stock=stock+%s,updated_at=CURRENT_TIMESTAMP WHERE id=%s",(item["quantity"],item["product_id"]))
                        db.execute("INSERT INTO stock_movements(product_id,product_name,quantity_change,reason,order_id) VALUES (%s,%s,%s,'Devolución por cancelación',%s)",(item["product_id"],item["product_name"],item["quantity"],oid))
                db.execute("UPDATE sales SET status='Cancelado' WHERE order_id=%s",(oid,))
            db.execute("UPDATE orders SET status=%s,updated_at=CURRENT_TIMESTAMP WHERE id=%s",(status,oid))
            db.execute("UPDATE sales SET status=%s WHERE order_id=%s",(status,oid))
            return self.send_json({"ok":True,"message":"Estado del pedido actualizado."})
        match=re.fullmatch(r"/api/admin/expenses/(\d+)",path)
        if match:
            eid=int(match.group(1))
            if method=="DELETE": db.execute("DELETE FROM expenses WHERE id=%s",(eid,)); return self.send_json({"ok":True})
            if method=="PUT":
                amount=integer(data.get("amount"),"Monto"); name=str(data.get("name","")).strip(); category=str(data.get("category","")).strip(); day=date.fromisoformat(str(data.get("date",date.today().isoformat())))
                if not name or not category: raise ValueError("Ingresá el nombre y la categoría del gasto.")
                db.execute("UPDATE expenses SET name=%s,category=%s,amount=%s,date=%s,description=%s WHERE id=%s",(name,category,amount,day,str(data.get("description","")).strip(),eid)); return self.send_json({"ok":True})
        match=re.fullmatch(r"/api/admin/stock/(\d+)",path)
        if match and method=="POST":
            pid=int(match.group(1)); quantity=integer(data.get("quantity"),"Cantidad",1); p=db.execute("SELECT * FROM products WHERE id=%s",(pid,)).fetchone()
            if not p: return self.send_json({"error":"Producto no encontrado."},404)
            db.execute("UPDATE products SET stock=stock+%s,updated_at=CURRENT_TIMESTAMP WHERE id=%s",(quantity,pid))
            db.execute("INSERT INTO stock_movements(product_id,product_name,quantity_change,reason) VALUES (%s,%s,%s,'Reposición manual')",(pid,p["name"],quantity))
            return self.send_json({"ok":True,"stock":p["stock"]+quantity})
        return self.send_json({"error":"No encontrado."},404)


if __name__ == "__main__":
    init_db()
    host=os.environ.get("NUTRIDULCE_HOST","0.0.0.0"); port=int(os.environ.get("PORT","8000"))
    print(f"NutriDulce disponible en http://{host}:{port} · PostgreSQL configurado")
    ThreadingHTTPServer((host,port),Handler).serve_forever()
